alias pa="php artisan"
alias pas="php artisan serve"
alias pam="php artisan migrate"
alias padbs="php artisan DB:seed"
alias pamf="php artisan migrate:fresh"
alias model="php artisan make:model"
alias cont="php artisan make:controller"
alias policy="php artisan make:policy"
alias middleware="php artisan make:middleware"
alias routes="php artisan route:list"
alias wip="git add . && git commit -m “wip” && git push"
alias gst="git status"
alias ni="npm install"
alias watch="npm run watch"
alias prod="npm run prod"
alias cr="composer require"
function table (){ php artisan make:migration create_$*_table;}